x-airflow-common: &airflow-common
  image: apache/airflow:2.7.3
  environment: &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session'
    PYTHONPATH: '/opt/airflow'
    AIRFLOW__CORE__DAG_FILE_PROCESSOR_TIMEOUT: 120
    AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: 10
    MINIO_ENDPOINT: "${MINIO_ENDPOINT:-http://minio:9000}"
    MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY:-minioadmin}"
    MINIO_SECRET_KEY: "${MINIO_SECRET_KEY:-minioadmin}"
    _PIP_ADDITIONAL_REQUIREMENTS: "minio pytesseract pillow pdf2image python-dotenv pdfplumber opencv-python-headless"
    VALIDATION_URL: "http://validation:8001"
  volumes:
    - ../airflow/dags:/opt/airflow/dags
    - ../airflow/scripts:/opt/airflow/scripts
    - ../airflow/data:/opt/airflow/data
    - ../data-lake:/opt/airflow/data_lake
    - airflow-logs:/opt/airflow/logs
    - airflow-plugins:/opt/airflow/plugins
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on: &airflow-common-depends-on
    postgres:
      condition: service_healthy

services:

  # ─────────────────────────────────────────
  # BASE DE DONNÉES — PostgreSQL (Airflow)
  # ─────────────────────────────────────────
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-airflow}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-airflow}
      POSTGRES_DB: ${POSTGRES_DB:-airflow}
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always

  # ─────────────────────────────────────────
  # DATA LAKE — MinIO (Responsable : Clément)
  # ─────────────────────────────────────────
  minio:
    image: minio/minio
    ports:
      - "9001:9000"
      - "9002:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      retries: 5
      start_period: 10s
    restart: always

  minio-init:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    entrypoint: >
      /bin/sh -c "
      mc alias set local http://minio:9000 $$MINIO_ROOT_USER $$MINIO_ROOT_USER;
      mc mb --ignore-existing local/raw;
      mc mb --ignore-existing local/clean;
      mc mb --ignore-existing local/curated;
      echo 'Buckets créés : raw, clean, curated';
      "

  # ─────────────────────────────────────────────────────
  # ORCHESTRATION — Airflow (Responsable : Chaimae)
  # ─────────────────────────────────────────────────────
  airflow-init:
      image: apache/airflow:2.7.3
      depends_on:
        postgres:
          condition: service_healthy
      environment:
        AIRFLOW__CORE__EXECUTOR: LocalExecutor
        AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW_URL:-postgresql+psycopg2://airflow:airflow@postgres/airflow}
        AIRFLOW__CORE__FERNET_KEY: ''
        AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      volumes:
        - ../airflow/dags:/opt/airflow/dags
        - ../airflow/scripts:/opt/airflow/scripts
        - ../airflow/data:/opt/airflow/data
        - airflow-logs:/opt/airflow/logs
        - airflow-plugins:/opt/airflow/plugins
      entrypoint: /bin/bash
      command:
        - -c
        - |
          python -m airflow db migrate
          python -m airflow users create \
            --username ${AIRFLOW_USER:-airflow} \
            --password ${AIRFLOW_PASSWORD:-airflow} \
            --firstname Admin \
            --lastname Admin \
            --role Admin \
            --email admin@example.com || true
          echo "Init termine."

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
      validation:
        condition: service_healthy

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8974/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
      validation:
        condition: service_healthy
  
  # ─────────────────────────────────────────────────────
  # VALIDATION — Service Awadi
  # ─────────────────────────────────────────────────────
  validation:
    build:
      context: ../validation
      dockerfile: Dockerfile
    container_name: validation
    ports:
      - "8001:8001"
    volumes:
      - ../datasets/output:/app/output
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 10s
      retries: 5
      start_period: 15s
    restart: always

volumes:
  postgres-db-volume:
  airflow-logs:
  airflow-plugins:
  minio-data:
