FROM apache/airflow:2.7.3

USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
    tesseract-ocr \
    tesseract-ocr-fra \
    poppler-utils \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

USER airflow