RULE_WEIGHTS = {
    "FORMAT_SIRET": 40,
    "LUHN_SIRET": 40,
    "ARITHMETIC_ERROR": 30,
    "TVA_INVALIDE": 30,
    "ATTESTATION_EXPIRED": 35,
    "SIRET_MISMATCH": 50,
    "DOUBLON_FACTURE": 50,
    "IBAN_CHANGE": 50,
    "INACTIVE_COMPANY": 60,
    "ML_ANOMALY": 40,
}

THRESHOLDS = {
    "CLEAN": 30,
    "WARNING": 70,
}

TOLERANCE_ARITHMETIQUE = 0.01
